import {DownloadOutlined,FileExcelOutlined,PlusOutlined,ReloadOutlined} from "@ant-design/icons";
import {App,Button,Checkbox,Form,Input,Modal,Select,Space,Switch,Table,Tag} from "antd";
import {useEffect,useMemo,useState} from "react";
import {api,downloadExportJob} from "../api";
import {PageTitle} from "../components";
import {formatDateTime} from "../time";

type Field={key:string;label:string};
type Template={id:string;name:string;format:string;fields:string[];is_default:boolean;is_active:boolean;creator_name:string;updated_at:string};
type Job={id:string;template_name:string;status:string;filename?:string;record_count:number;error?:string;attempt_count:number;download_ready:boolean;created_at:string;completed_at?:string;expires_at?:string};

export default function Templates(){
 const {message}=App.useApp(); const [fields,setFields]=useState<Field[]>([]),[templates,setTemplates]=useState<Template[]>([]),[jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<string>(),[modal,setModal]=useState(false),[creating,setCreating]=useState(false),[exporting,setExporting]=useState(false); const [form]=Form.useForm();
 async function load(){try{const [fieldData,templateData,jobData]=await Promise.all([api.request<Field[]>("/export-templates/fields"),api.request<Template[]>("/export-templates?include_inactive=true"),api.request<Job[]>("/exports")]);setFields(fieldData);setTemplates(templateData);setJobs(jobData);setSelected(current=>current||templateData.find(x=>x.is_default&&x.is_active)?.id||templateData.find(x=>x.is_active)?.id)}catch(e:any){message.error(e.message)}}
 useEffect(()=>{load()},[]); useEffect(()=>{if(!jobs.some(job=>["PENDING","PROCESSING"].includes(job.status)))return;const timer=window.setInterval(load,1800);return()=>window.clearInterval(timer)},[jobs]);
 const fieldLabels=useMemo(()=>Object.fromEntries(fields.map(field=>[field.key,field.label])),[fields]);
 async function createTemplate(){setCreating(true);try{const values=await form.validateFields();await api.request("/export-templates",{method:"POST",body:JSON.stringify(values)});message.success("Excel 模板已创建");setModal(false);form.resetFields();await load()}catch(e:any){if(e?.errorFields)return;message.error(e.message)}finally{setCreating(false)}}
 async function toggle(item:Template,active:boolean){try{await api.request(`/export-templates/${item.id}`,{method:"PATCH",body:JSON.stringify({is_active:active})});message.success(active?"模板已启用":"模板已停用");await load()}catch(e:any){message.error(e.message)}}
 async function makeDefault(item:Template){try{await api.request(`/export-templates/${item.id}`,{method:"PATCH",body:JSON.stringify({is_default:true,is_active:true})});message.success("已设为默认模板");setSelected(item.id);await load()}catch(e:any){message.error(e.message)}}
 async function createExport(){if(!selected)return message.warning("请先选择模板");setExporting(true);try{const job=await api.request<Job>("/exports",{method:"POST",body:JSON.stringify({template_id:selected})});message.success("导出任务已创建，完成后可下载");setJobs(items=>[job,...items]);window.setTimeout(load,600)}catch(e:any){message.error(e.message)}finally{setExporting(false)}}
 async function download(job:Job){try{await downloadExportJob(job.id,job.filename||"项目记录汇总.xlsx");message.success("Excel 文件已开始下载")}catch(e:any){message.error(e.message)}}
 async function retry(job:Job){try{const updated=await api.request<Job>(`/exports/${job.id}/retry`,{method:"POST"});setJobs(items=>items.map(item=>item.id===job.id?updated:item));message.success("导出任务已重新提交");window.setTimeout(load,600)}catch(e:any){message.error(e.message)}}
 return <><PageTitle title="模板中心" sub="配置 Excel 导出字段与顺序，后台生成完成后从任务列表下载" extra={<Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>{form.setFieldsValue({fields:templates.find(x=>x.is_default)?.fields||fields.slice(0,9).map(x=>x.key),is_default:false});setModal(true)}}>新增模板</Button></Space>}/>
  <section className="card export-launch"><div><FileExcelOutlined/><span><b>创建项目记录 Excel</b><small>按当前账号的数据权限导出，最多生成 5,000 条记录。</small></span></div><Space><Select value={selected} onChange={setSelected} placeholder="选择导出模板" style={{width:260}} options={templates.filter(x=>x.is_active).map(x=>({value:x.id,label:`${x.name}${x.is_default?"（默认）":""}`}))}/><Button type="primary" loading={exporting} icon={<FileExcelOutlined/>} onClick={createExport}>生成 Excel</Button></Space></section>
  <section className="card table-card"><h3>导出模板</h3><Table rowKey="id" pagination={false} dataSource={templates} columns={[{title:"模板名称",dataIndex:"name",render:(value:string,row:Template)=><Space><b>{value}</b>{row.is_default&&<Tag color="green">默认</Tag>}</Space>},{title:"导出字段",dataIndex:"fields",render:(values:string[])=><div className="field-tags">{values.map(value=><Tag key={value}>{fieldLabels[value]||value}</Tag>)}</div>},{title:"创建者",dataIndex:"creator_name",width:100},{title:"状态",width:100,render:(_:unknown,row:Template)=><Switch checked={row.is_active} checkedChildren="启用" unCheckedChildren="停用" onChange={checked=>toggle(row,checked)}/>},{title:"操作",width:110,render:(_:unknown,row:Template)=><Button type="link" disabled={row.is_default} onClick={()=>makeDefault(row)}>设为默认</Button>}]}/></section>
  <section className="card table-card export-jobs"><h3>导出任务</h3><Table rowKey="id" dataSource={jobs} pagination={{pageSize:8}} locale={{emptyText:"尚未创建 Excel 导出任务"}} columns={[{title:"创建时间",dataIndex:"created_at",width:170,render:(v:string)=>formatDateTime(v)},{title:"模板",dataIndex:"template_name"},{title:"记录数",dataIndex:"record_count",width:85,render:(v:number)=>`${v} 条`},{title:"状态",dataIndex:"status",width:100,render:(v:string)=><Tag color={v==="COMPLETED"?"green":v==="FAILED"?"red":v==="EXPIRED"?"default":"blue"}>{({PENDING:"等待中",PROCESSING:"生成中",COMPLETED:"已完成",FAILED:"失败",EXPIRED:"已过期"} as any)[v]||v}</Tag>},{title:"有效期",dataIndex:"expires_at",width:170,render:(v:string)=>v?formatDateTime(v):"—"},{title:"文件",dataIndex:"filename",ellipsis:true,render:(v:string,row:Job)=>v||row.error||"—"},{title:"操作",width:105,render:(_:unknown,row:Job)=>["FAILED","EXPIRED"].includes(row.status)?<Button icon={<ReloadOutlined/>} onClick={()=>retry(row)}>重试</Button>:<Button icon={<DownloadOutlined/>} disabled={!row.download_ready} onClick={()=>download(row)}>下载</Button>}]}/></section>
  <Modal title="新增 Excel 导出模板" open={modal} onCancel={()=>setModal(false)} onOk={createTemplate} confirmLoading={creating} okText="创建模板"><Form form={form} layout="vertical"><Form.Item name="name" label="模板名称" rules={[{required:true,message:"请输入模板名称"}]}><Input maxLength={120} placeholder="例如：项目周会记录模板"/></Form.Item><Form.Item name="fields" label="导出字段与顺序" rules={[{required:true,message:"请至少选择一个字段"}]} extra="当前按选项顺序导出；可取消不需要的字段。"><Checkbox.Group className="template-fields" options={fields.map(field=>({label:field.label,value:field.key}))}/></Form.Item><Form.Item name="is_default" valuePropName="checked"><Checkbox>设为默认模板</Checkbox></Form.Item></Form></Modal>
 </>;
}
