from enum import StrEnum
class RoleCode(StrEnum): ENGINEER="ENGINEER"; PROJECT_MANAGER="PROJECT_MANAGER"; DEPARTMENT_HEAD="DEPARTMENT_HEAD"; SUPER_ADMIN="SUPER_ADMIN"
class UserStatus(StrEnum): ACTIVE="ACTIVE"; DISABLED="DISABLED"
class RecordStatus(StrEnum):
    DRAFT="DRAFT"; SUBMITTED="SUBMITTED"; AI_PROCESSING="AI_PROCESSING"; AI_REVIEW_REQUIRED="AI_REVIEW_REQUIRED"; READY_TO_ASSIGN="READY_TO_ASSIGN"; ASSIGNED="ASSIGNED"; IN_PROGRESS="IN_PROGRESS"; WAITING_SUPPLEMENT="WAITING_SUPPLEMENT"; RESOLVED="RESOLVED"; CLOSED="CLOSED"; REJECTED="REJECTED"; CANCELLED="CANCELLED"
class Priority(StrEnum): LOW="LOW"; MEDIUM="MEDIUM"; HIGH="HIGH"; URGENT="URGENT"
class MediaType(StrEnum): IMAGE="IMAGE"; AUDIO="AUDIO"; FILE="FILE"
class TaskStatus(StrEnum): PENDING="PENDING"; IN_PROGRESS="IN_PROGRESS"; DONE="DONE"; CANCELLED="CANCELLED"
